# Application Configuration
spring:
  application:
    name: PolicyManagementAPI
  
  # Database Configuration
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
    
  h2:
    console:
      enabled: true
      path: /h2-console
      
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        
  # Jackson Configuration
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false

# Server Configuration  
server:
  port: 8080
  servlet:
    context-path: /api

# Management Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

# Logging Configuration
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# External Services Configuration
external:
  services:
    payment-service:
      url: /api/v1/payments
    payment-service:
      timeout: 30000
    payment-service:
      circuit-breaker:
      enabled: true
    payment-service:
      retry:
      max-attempts: 3
    notification-service:
      url: /api/v1/notifications
    notification-service:
      timeout: 30000
    notification-service:
      circuit-breaker:
      enabled: true
    notification-service:
      retry:
      max-attempts: 3
    document-service:
      url: /api/v1/documents
    document-service:
      timeout: 30000
    document-service:
      circuit-breaker:
      enabled: true
    document-service:
      retry:
      max-attempts: 3
    credit-bureau-service:
      url: /api/v1/credit-check
    credit-bureau-service:
      timeout: 30000
    credit-bureau-service:
      circuit-breaker:
      enabled: true
    credit-bureau-service:
      retry:
      max-attempts: 3
    medical-information-bureau:
      url: /api/v1/medical-records
    medical-information-bureau:
      timeout: 30000
    medical-information-bureau:
      circuit-breaker:
      enabled: true
    medical-information-bureau:
      retry:
      max-attempts: 3
    motor-vehicle-records:
      url: /api/v1/mvr
    motor-vehicle-records:
      timeout: 30000
    motor-vehicle-records:
      circuit-breaker:
      enabled: true
    motor-vehicle-records:
      retry:
      max-attempts: 3
    property-data-service:
      url: /api/v1/property
    property-data-service:
      timeout: 30000
    property-data-service:
      circuit-breaker:
      enabled: true
    property-data-service:
      retry:
      max-attempts: 3
    actuarial-service:
      url: /api/v1/actuarial
    actuarial-service:
      timeout: 30000
    actuarial-service:
      circuit-breaker:
      enabled: true
    actuarial-service:
      retry:
      max-attempts: 3


# OpenAPI Documentation
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method